import Head from 'next/head';
import { AboutPage } from '../components/about/about-page';
import { HomePage } from '../components/home/homePage';
import { PlasteringPage } from '../components/plastering/plastering-page';
import { RenderingPage } from '../components/rendering/rendering-page';
import Contact from './contact';

export default function Index() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div className='overflow-y-auto overflow-x-hidden'>
        <HomePage />
        <AboutPage />
        <PlasteringPage />
        <RenderingPage />
        <Contact />
      </div>
    </>
  );
}
