import Head from 'next/head';
import ContactPage from '../components/_pages/contact/contact';
import { HomePage } from '../components/_pages/home/homePage';
import { PlasteringPage } from '../components/_pages/plastering/plastering-page';
import { RenderingPage } from '../components/_pages/rendering/rendering-page';

export default function Index() {
  return (
    <>
      <Head>
        <title>Southern Wall Tech</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div className='grid gap-20'>
        <HomePage />
        <PlasteringPage />
        <RenderingPage />
        <ContactPage />
      </div>
    </>
  );
}
